"""
Unit Tests - Metadata Detector

SDLC Stage: 04 - BUILD
Sprint: 42 - AI Detection & Validation Pipeline
Framework: SDLC 5.1.1

Purpose:
Unit tests for MetadataDetector covering:
1. Tool detection from PR title
2. Tool detection from PR body
3. Tool detection from commit messages
4. Combined scoring (title + body + commits)
5. Multiple tool matches (highest score wins)

Coverage Target: 95%+
"""

import pytest

from app.services.ai_detection import AIToolType, DetectionMethod
from app.services.ai_detection.metadata_detector import MetadataDetector


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def detector():
    """Create MetadataDetector instance."""
    return MetadataDetector()


# ============================================================================
# Test Tool Detection from Title
# ============================================================================


@pytest.mark.asyncio
async def test_detect_cursor_from_title(detector):
    """Test Cursor detection from PR title."""
    pr_data = {
        "title": "feat: add login with Cursor",
        "body": "",
    }
    commits = [{"commit": {"message": "initial commit"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR
    assert result.confidence > 0.0
    assert "title" in result.evidence["matched_in"]


@pytest.mark.asyncio
async def test_detect_copilot_from_title(detector):
    """Test GitHub Copilot detection from PR title."""
    pr_data = {
        "title": "refactor: code improvements (GitHub Copilot)",
        "body": "",
    }
    commits = [{"commit": {"message": "refactor code"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.COPILOT
    assert "title" in result.evidence["matched_in"]


@pytest.mark.asyncio
async def test_detect_claude_from_title(detector):
    """Test Claude Code detection from PR title."""
    pr_data = {
        "title": "feat: implement auth [Claude Code]",
        "body": "",
    }
    commits = [{"commit": {"message": "implement auth"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CLAUDE_CODE


@pytest.mark.asyncio
async def test_detect_chatgpt_from_title(detector):
    """Test ChatGPT detection from PR title."""
    pr_data = {
        "title": "fix: bug fixes generated by ChatGPT",
        "body": "",
    }
    commits = [{"commit": {"message": "fix bugs"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CHATGPT


# ============================================================================
# Test Tool Detection from Body
# ============================================================================


@pytest.mark.asyncio
async def test_detect_cursor_from_body(detector):
    """Test Cursor detection from PR body."""
    pr_data = {
        "title": "Add new feature",
        "body": "This code was generated using Cursor AI assistant.",
    }
    commits = [{"commit": {"message": "add feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR
    assert "body" in result.evidence["matched_in"]


@pytest.mark.asyncio
async def test_detect_windsurf_from_body(detector):
    """Test Windsurf detection from PR body."""
    pr_data = {
        "title": "Update docs",
        "body": "Generated with Codeium Windsurf",
    }
    commits = [{"commit": {"message": "update docs"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.WINDSURF


# ============================================================================
# Test Tool Detection from Commits
# ============================================================================


@pytest.mark.asyncio
async def test_detect_cursor_from_commits(detector):
    """Test Cursor detection from commit messages."""
    pr_data = {
        "title": "Add feature",
        "body": "",
    }
    commits = [
        {"commit": {"message": "feat: add login (Cursor)"}},
        {"commit": {"message": "fix: typo"}},
        {"commit": {"message": "refactor: cleanup (Cursor)"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR
    assert "commits (2/3)" in result.evidence["matched_in"]


# ============================================================================
# Test Combined Scoring
# ============================================================================


@pytest.mark.asyncio
async def test_combined_scoring_all_sources(detector):
    """Test scoring from title + body + commits."""
    pr_data = {
        "title": "feat: add auth (Cursor)",
        "body": "Generated by Cursor AI",
    }
    commits = [
        {"commit": {"message": "Cursor: add auth"}},
        {"commit": {"message": "Cursor: fix typo"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR
    # Should have high confidence (all sources match)
    assert result.confidence > 0.8


@pytest.mark.asyncio
async def test_combined_scoring_partial_match(detector):
    """Test scoring with partial matches."""
    pr_data = {
        "title": "Add feature",
        "body": "Generated by Cursor",
    }
    commits = [
        {"commit": {"message": "add feature"}},
        {"commit": {"message": "fix bug"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is False  # Only body matches (30% weight)
    assert result.confidence < 0.5


# ============================================================================
# Test Multiple Tool Matches
# ============================================================================


@pytest.mark.asyncio
async def test_multiple_tools_highest_wins(detector):
    """Test that highest scoring tool wins when multiple detected."""
    pr_data = {
        "title": "feat: add login (Cursor)",
        "body": "Also used Claude for some parts",
    }
    commits = [
        {"commit": {"message": "Cursor: main implementation"}},
        {"commit": {"message": "Claude: minor fixes"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    # Cursor should win (title + 50% commits vs Claude body + 50% commits)
    assert result.tool == AIToolType.CURSOR
    assert result.evidence["best_match"] == "cursor"


# ============================================================================
# Test No Detection
# ============================================================================


@pytest.mark.asyncio
async def test_no_ai_detection(detector):
    """Test human-written PR with no AI markers."""
    pr_data = {
        "title": "fix: typo in README",
        "body": "Fixed a spelling mistake",
    }
    commits = [{"commit": {"message": "fix typo"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is False
    assert result.confidence == 0.0
    assert result.tool is None
    assert result.method == DetectionMethod.METADATA


@pytest.mark.asyncio
async def test_empty_pr_data(detector):
    """Test detection with empty PR data."""
    pr_data = {"title": "", "body": ""}
    commits = []

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is False
    assert result.confidence == 0.0


# ============================================================================
# Test Edge Cases
# ============================================================================


@pytest.mark.asyncio
async def test_case_insensitive_matching(detector):
    """Test that pattern matching is case-insensitive."""
    pr_data = {
        "title": "feat: add feature (CURSOR)",
        "body": "Generated by CuRsOr AI",
    }
    commits = [{"commit": {"message": "cursor code"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


@pytest.mark.asyncio
async def test_tool_name_in_code_snippet(detector):
    """Test detection when tool name appears in code snippet."""
    pr_data = {
        "title": "Add cursor implementation",
        "body": "Implements database cursor functionality",
    }
    commits = [{"commit": {"message": "add cursor class"}}]

    result = await detector.detect(pr_data, commits, "")

    # Should detect CURSOR (even though it's database cursor)
    # This is a known limitation of metadata detection
    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


@pytest.mark.asyncio
async def test_copilot_emoji_detection(detector):
    """Test GitHub Copilot detection via 🤖 emoji."""
    pr_data = {
        "title": "feat: add feature 🤖",
        "body": "",
    }
    commits = [{"commit": {"message": "add feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.COPILOT


# ============================================================================
# Test Tool-Specific Patterns
# ============================================================================


@pytest.mark.asyncio
async def test_detect_tabnine(detector):
    """Test Tabnine detection."""
    pr_data = {
        "title": "Code completion via Tabnine",
        "body": "",
    }
    commits = [{"commit": {"message": "add feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.TABNINE


@pytest.mark.asyncio
async def test_detect_cody(detector):
    """Test Sourcegraph Cody detection."""
    pr_data = {
        "title": "Feature generated by Cody",
        "body": "",
    }
    commits = [{"commit": {"message": "add feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CODY
