"""
Unit Tests - Commit Detector

SDLC Stage: 04 - BUILD
Sprint: 42 - AI Detection & Validation Pipeline
Framework: SDLC 5.1.1

Purpose:
Unit tests for CommitDetector covering:
1. Co-authored-by patterns (GitHub Copilot)
2. Generated-by patterns (Cursor, Claude, ChatGPT)
3. Tool-specific commit tags
4. High confidence scoring (0.9)

Coverage Target: 95%+
"""

import pytest

from app.services.ai_detection import AIToolType, DetectionMethod
from app.services.ai_detection.commit_detector import CommitDetector


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def detector():
    """Create CommitDetector instance."""
    return CommitDetector()


# ============================================================================
# Test GitHub Copilot Detection
# ============================================================================


@pytest.mark.asyncio
async def test_detect_copilot_coauthored(detector):
    """Test Copilot detection via co-authored-by."""
    pr_data = {"title": "Add feature", "body": ""}
    commits = [
        {
            "sha": "abc123",
            "commit": {
                "message": "feat: add login\n\nCo-authored-by: GitHub Copilot <noreply@github.com>"
            },
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.COPILOT
    assert result.confidence == 0.9  # High confidence
    assert result.method == DetectionMethod.COMMIT_MESSAGE
    assert result.evidence["commit_sha"] == "abc123"


@pytest.mark.asyncio
async def test_detect_copilot_generated_by(detector):
    """Test Copilot detection via 'generated by copilot'."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "def456",
            "commit": {"message": "[copilot] refactor code\n\nGenerated by Copilot"},
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.COPILOT
    assert result.confidence == 0.9


@pytest.mark.asyncio
async def test_detect_copilot_tag(detector):
    """Test Copilot detection via [copilot] tag."""
    pr_data = {"title": "", "body": ""}
    commits = [{"sha": "ghi789", "commit": {"message": "[copilot] add feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.COPILOT


# ============================================================================
# Test Cursor Detection
# ============================================================================


@pytest.mark.asyncio
async def test_detect_cursor_generated_by(detector):
    """Test Cursor detection via 'generated by cursor'."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "cursor123",
            "commit": {"message": "feat: implement auth\n\nGenerated by Cursor"},
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR
    assert result.confidence == 0.9
    assert "Generated by Cursor" in result.evidence["commit_message_preview"]


@pytest.mark.asyncio
async def test_detect_cursor_tag(detector):
    """Test Cursor detection via [cursor] tag."""
    pr_data = {"title": "", "body": ""}
    commits = [{"sha": "cursor456", "commit": {"message": "[cursor] refactor code"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


@pytest.mark.asyncio
async def test_detect_cursor_domain(detector):
    """Test Cursor detection via cursor.sh mention."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {"sha": "cursor789", "commit": {"message": "Generated via cursor.sh"}}
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


# ============================================================================
# Test Claude Code Detection
# ============================================================================


@pytest.mark.asyncio
async def test_detect_claude_generated_with(detector):
    """Test Claude detection via 'generated with claude'."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "claude123",
            "commit": {
                "message": "feat: add API\n\nGenerated with Claude Code by Anthropic"
            },
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CLAUDE_CODE
    assert result.confidence == 0.9


@pytest.mark.asyncio
async def test_detect_claude_tag(detector):
    """Test Claude detection via [claude] tag."""
    pr_data = {"title": "", "body": ""}
    commits = [{"sha": "claude456", "commit": {"message": "[claude] implement feature"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CLAUDE_CODE


# ============================================================================
# Test ChatGPT Detection
# ============================================================================


@pytest.mark.asyncio
async def test_detect_chatgpt_generated_by(detector):
    """Test ChatGPT detection via 'generated by chatgpt'."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "gpt123",
            "commit": {"message": "fix: bug fixes\n\nGenerated by ChatGPT"},
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CHATGPT
    assert result.confidence == 0.9


@pytest.mark.asyncio
async def test_detect_chatgpt_tag(detector):
    """Test ChatGPT detection via [chatgpt] tag."""
    pr_data = {"title": "", "body": ""}
    commits = [{"sha": "gpt456", "commit": {"message": "[chatgpt] refactor code"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CHATGPT


@pytest.mark.asyncio
async def test_detect_openai_gpt(detector):
    """Test ChatGPT detection via 'openai gpt' mention."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {"sha": "gpt789", "commit": {"message": "Code review by OpenAI GPT-4"}}
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CHATGPT


# ============================================================================
# Test Other Tools
# ============================================================================


@pytest.mark.asyncio
async def test_detect_windsurf(detector):
    """Test Windsurf detection."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {"sha": "wind123", "commit": {"message": "[windsurf] generate code"}}
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.WINDSURF


@pytest.mark.asyncio
async def test_detect_cody(detector):
    """Test Cody detection."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "cody123",
            "commit": {"message": "Generated by Sourcegraph Cody"},
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CODY


@pytest.mark.asyncio
async def test_detect_tabnine(detector):
    """Test Tabnine detection."""
    pr_data = {"title": "", "body": ""}
    commits = [{"sha": "tab123", "commit": {"message": "[tabnine] code completion"}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.TABNINE


# ============================================================================
# Test No Detection
# ============================================================================


@pytest.mark.asyncio
async def test_no_ai_pattern_in_commits(detector):
    """Test human-written commits with no AI patterns."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {"sha": "abc123", "commit": {"message": "fix: typo in README"}},
        {"sha": "def456", "commit": {"message": "refactor: cleanup code"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is False
    assert result.confidence == 0.0
    assert result.tool is None
    assert result.evidence["scanned_commits"] == 2


@pytest.mark.asyncio
async def test_empty_commits(detector):
    """Test detection with no commits."""
    pr_data = {"title": "", "body": ""}
    commits = []

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is False
    assert result.confidence == 0.0


# ============================================================================
# Test Edge Cases
# ============================================================================


@pytest.mark.asyncio
async def test_case_insensitive_pattern_matching(detector):
    """Test case-insensitive pattern matching."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "case123",
            "commit": {"message": "GENERATED BY CURSOR"},  # Uppercase
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


@pytest.mark.asyncio
async def test_first_match_wins(detector):
    """Test that first matching commit wins (short-circuit)."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {"sha": "commit1", "commit": {"message": "[cursor] add feature"}},
        {"sha": "commit2", "commit": {"message": "[copilot] refactor"}},
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR  # First match
    assert result.evidence["commit_sha"] == "commit1"


@pytest.mark.asyncio
async def test_multiline_commit_message(detector):
    """Test detection in multiline commit messages."""
    pr_data = {"title": "", "body": ""}
    commits = [
        {
            "sha": "multiline123",
            "commit": {
                "message": """feat: implement authentication

This commit adds user authentication.

Generated by Cursor AI.

Reviewed by: @reviewer
"""
            },
        }
    ]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert result.tool == AIToolType.CURSOR


@pytest.mark.asyncio
async def test_commit_message_preview_truncation(detector):
    """Test that commit message preview is truncated to 200 chars."""
    pr_data = {"title": "", "body": ""}
    long_message = "Generated by Cursor. " + ("x" * 300)
    commits = [{"sha": "long123", "commit": {"message": long_message}}]

    result = await detector.detect(pr_data, commits, "")

    assert result.detected is True
    assert len(result.evidence["commit_message_preview"]) == 200
