"""
Unit Tests - GitHubAIDetectionService

SDLC Stage: 04 - BUILD
Sprint: 42 - AI Detection & Validation Pipeline
Framework: SDLC 5.1.1

Purpose:
Unit tests for GitHubAIDetectionService covering:
1. Combined weighted voting (40% metadata, 40% commit, 20% pattern)
2. Decision threshold (0.50)
3. Tool selection (highest confidence wins)
4. Evidence aggregation from all detectors
5. Performance (<600ms target)

Coverage Target: 95%+
"""

import pytest

from app.services.ai_detection import AIToolType, DetectionMethod
from app.services.ai_detection.service import GitHubAIDetectionService


# ============================================================================
# Fixtures
# ============================================================================


@pytest.fixture
def service():
    """Create GitHubAIDetectionService instance."""
    return GitHubAIDetectionService()


# ============================================================================
# Test Combined Detection - All Positive
# ============================================================================


@pytest.mark.asyncio
async def test_combined_all_detectors_agree_cursor(service):
    """Test when all detectors agree on Cursor."""
    pr_data = {
        "title": "feat: add login (Cursor)",
        "body": "Generated by Cursor AI",
    }
    commits = [
        {"sha": "abc123", "commit": {"message": "[cursor] implement auth"}},
        {"sha": "def456", "commit": {"message": "[cursor] add tests"}},
    ]
    diff = """
# Comment line 1
# Comment line 2
# Comment line 3
# Comment line 4
# Comment line 5

def login():
    data1 = get_user()
    result2 = validate(data1)
"""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is True
    assert result.detected_tool == AIToolType.CURSOR
    assert result.confidence > 0.7  # All detectors positive
    assert result.detection_method == DetectionMethod.COMBINED
    assert set(result.strategies_used) == {"metadata", "commit", "pattern"}


# ============================================================================
# Test Combined Detection - Partial Agreement
# ============================================================================


@pytest.mark.asyncio
async def test_combined_metadata_and_commit_only(service):
    """Test when metadata and commit agree, pattern doesn't."""
    pr_data = {
        "title": "feat: add API (Claude)",
        "body": "Generated with Claude Code",
    }
    commits = [{"sha": "abc123", "commit": {"message": "[claude] implement API"}}]
    diff = """
def create_api():
    \"\"\"Well-written code with no AI patterns.\"\"\"
    user = fetch_user()
    return validate_and_save(user)
"""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is True  # 40% + 40% = 80% confidence
    assert result.detected_tool == AIToolType.CLAUDE_CODE
    assert result.confidence >= 0.5


# ============================================================================
# Test Combined Detection - Threshold Boundary
# ============================================================================


@pytest.mark.asyncio
async def test_threshold_at_050_detected(service):
    """Test detection exactly at 0.50 threshold."""
    pr_data = {
        "title": "Add feature",
        "body": "Generated by Copilot",  # 30% metadata (body only)
    }
    commits = [{"sha": "abc123", "commit": {"message": "[copilot] add feature"}}]  # 40% commit
    diff = ""  # No pattern detection

    result = await service.detect(pr_data, commits, diff)

    # metadata (body only) ~30% * 0.4 = 12% + commit 90% * 0.4 = 36% = 48%
    # Should be right at threshold
    assert result.confidence < 0.55  # Close to threshold


@pytest.mark.asyncio
async def test_threshold_below_050_not_detected(service):
    """Test no detection when below 0.50 threshold."""
    pr_data = {
        "title": "Add feature",
        "body": "Mentioned copilot in passing",  # Weak signal
    }
    commits = [{"sha": "abc123", "commit": {"message": "add feature"}}]
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is False
    assert result.confidence < 0.5


# ============================================================================
# Test Tool Selection
# ============================================================================


@pytest.mark.asyncio
async def test_highest_confidence_tool_wins(service):
    """Test that highest confidence detector's tool wins."""
    pr_data = {
        "title": "Add feature",
        "body": "Mentioned claude briefly",  # Weak Claude signal
    }
    commits = [
        {"sha": "abc123", "commit": {"message": "[cursor] main implementation"}},
        {"sha": "def456", "commit": {"message": "[cursor] add tests"}},
    ]  # Strong Cursor signal
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    # Cursor should win (commit detector 90% confidence)
    assert result.detected_tool == AIToolType.CURSOR


# ============================================================================
# Test No Detection
# ============================================================================


@pytest.mark.asyncio
async def test_no_ai_detected_all_negative(service):
    """Test when all detectors return negative."""
    pr_data = {
        "title": "fix: typo in README",
        "body": "Fixed spelling mistake",
    }
    commits = [{"sha": "abc123", "commit": {"message": "fix typo"}}]
    diff = """
def calculate_total(items):
    \"\"\"Calculate total price.\"\"\"
    return sum(item.price for item in items)
"""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is False
    assert result.confidence < 0.5
    assert result.detected_tool is None


# ============================================================================
# Test Evidence Aggregation
# ============================================================================


@pytest.mark.asyncio
async def test_evidence_aggregation(service):
    """Test that evidence from all detectors is aggregated."""
    pr_data = {
        "title": "feat: add auth (Cursor)",
        "body": "",
    }
    commits = [{"sha": "abc123", "commit": {"message": "[cursor] implement"}}]
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    # Check evidence structure
    assert "metadata" in result.detection_evidence
    assert "commit" in result.detection_evidence
    assert "pattern" in result.detection_evidence
    assert "weights" in result.detection_evidence
    assert "individual_confidences" in result.detection_evidence

    # Check weights are correct
    assert result.detection_evidence["weights"]["metadata"] == 0.4
    assert result.detection_evidence["weights"]["commit"] == 0.4
    assert result.detection_evidence["weights"]["pattern"] == 0.2


# ============================================================================
# Test Performance
# ============================================================================


@pytest.mark.asyncio
async def test_detection_latency_under_600ms(service):
    """Test that detection completes in <600ms (p95 target)."""
    pr_data = {
        "title": "feat: implement API (Cursor)",
        "body": "Generated by Cursor AI",
    }
    commits = [
        {"sha": f"commit{i}", "commit": {"message": f"[cursor] task {i}"}}
        for i in range(10)
    ]  # 10 commits
    diff = "def function(): pass\n" * 100  # Large diff

    result = await service.detect(pr_data, commits, diff)

    # Should complete quickly (all local pattern matching)
    assert result.detection_duration_ms < 600


# ============================================================================
# Test Edge Cases
# ============================================================================


@pytest.mark.asyncio
async def test_empty_pr_data(service):
    """Test with empty PR data."""
    pr_data = {"title": "", "body": ""}
    commits = []
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is False
    assert result.confidence == 0.0


@pytest.mark.asyncio
async def test_mixed_tool_signals(service):
    """Test with conflicting tool signals."""
    pr_data = {
        "title": "feat: add API (Cursor)",  # Cursor in title
        "body": "Used Claude Code",  # Claude in body
    }
    commits = [
        {"sha": "abc123", "commit": {"message": "[copilot] implement"}}
    ]  # Copilot in commit
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    assert result.is_ai_generated is True
    # One of the tools should win (highest confidence)
    assert result.detected_tool in [
        AIToolType.CURSOR,
        AIToolType.CLAUDE_CODE,
        AIToolType.COPILOT,
    ]


# ============================================================================
# Test Weighted Voting
# ============================================================================


@pytest.mark.asyncio
async def test_weighted_voting_formula(service):
    """Test that weighted voting formula is correct."""
    pr_data = {
        "title": "feat: add login (Cursor)",  # Title match = high metadata confidence
        "body": "",
    }
    commits = []  # No commit patterns
    diff = """
# Comment 1
# Comment 2
# Comment 3
# Comment 4
# Comment 5
"""  # Some pattern detection

    result = await service.detect(pr_data, commits, diff)

    # Verify individual confidences are captured
    assert "metadata" in result.detection_evidence["individual_confidences"]
    assert "commit" in result.detection_evidence["individual_confidences"]
    assert "pattern" in result.detection_evidence["individual_confidences"]

    # Metadata should have high confidence (title match)
    metadata_conf = result.detection_evidence["individual_confidences"]["metadata"]
    assert metadata_conf > 0.3  # Title contributes 40% weight


# ============================================================================
# Test Model Extraction
# ============================================================================


@pytest.mark.asyncio
async def test_model_extraction_from_metadata(service):
    """Test extraction of AI model name from metadata."""
    pr_data = {
        "title": "feat: add API",
        "body": "Generated using GPT-4-turbo model",
    }
    commits = [{"sha": "abc123", "commit": {"message": "[chatgpt] implement API"}}]
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    # Should detect ChatGPT and extract model
    assert result.detected_tool == AIToolType.CHATGPT
    # Model extraction may or may not work (depends on evidence format)
    # Just ensure no crash


@pytest.mark.asyncio
async def test_claude_model_extraction(service):
    """Test extraction of Claude model."""
    pr_data = {
        "title": "feat: add feature",
        "body": "Generated with Claude-3-Opus",
    }
    commits = [{"sha": "abc123", "commit": {"message": "[claude] implement"}}]
    diff = ""

    result = await service.detect(pr_data, commits, diff)

    assert result.detected_tool == AIToolType.CLAUDE_CODE
    # Model extraction is best-effort
    assert result is not None


# ============================================================================
# Test Parallel Execution
# ============================================================================


@pytest.mark.asyncio
async def test_parallel_detector_execution(service):
    """Test that detectors run in parallel (asyncio.gather)."""
    pr_data = {"title": "feat: add feature (Cursor)", "body": ""}
    commits = [{"sha": "abc123", "commit": {"message": "[cursor] implement"}}]
    diff = "def func(): pass"

    result = await service.detect(pr_data, commits, diff)

    # Should complete quickly due to parallel execution
    assert result.detection_duration_ms < 600

    # All strategies should be used
    assert "metadata" in result.strategies_used
    assert "commit" in result.strategies_used
    assert "pattern" in result.strategies_used
