"""
Commit Message Detector - AI Detection Strategy

SDLC Stage: 04 - BUILD
Sprint: 42 - AI Detection & Validation Pipeline
Framework: SDLC 5.1.1

Purpose:
Detect AI tools from commit message patterns.
Uses regex pattern matching for AI tool signatures.

Detection Approach:
- Regex patterns for co-authored-by, generated-by tags
- Tool-specific commit message conventions
- Higher confidence than metadata (0.9 vs 0.8)

Patterns Detected:
- GitHub Copilot: "co-authored-by: GitHub Copilot"
- Cursor: "Generated by Cursor", "[cursor]"
- Claude Code: "Generated with Claude Code"
"""

import re
from typing import Dict, List

from . import AIDetectionStrategy, AIToolType, DetectionMethod, DetectionResult


class CommitDetector(AIDetectionStrategy):
    """Detect AI tools from commit message patterns."""

    # False positive protection patterns (CTO P0 - Sprint 42 Day 5)
    # These patterns indicate NON-AI contexts for ambiguous keywords
    FALSE_POSITIVE_PATTERNS: Dict[AIToolType, List[str]] = {
        AIToolType.CURSOR: [
            r"database\s+cursor",
            r"db\s+cursor",
            r"cursor\s+position",
            r"cursor\s+leak",
            r"fix\s+cursor\s+position",
            r"cursor\s+handling",
        ],
        AIToolType.COPILOT: [
            r"co-?pilot\s+seat",
            r"autopilot",
            r"pilot\s+project",
        ],
        AIToolType.CLAUDE_CODE: [
            r"claude\s+shannon",
        ],
        AIToolType.WINDSURF: [
            r"windsurf\s+event",
            r"windsurf\s+handler",
            r"windsurf\s+sport",
        ],
        AIToolType.CODY: [
            r"cody\s+bear",
            r"cody\s+mascot",
        ],
    }

    # Commit message patterns (regex)
    # Expanded patterns for Sprint 42 Day 5 accuracy target (≥85%)
    COMMIT_PATTERNS: Dict[AIToolType, List[str]] = {
        AIToolType.COPILOT: [
            r"co-authored-by:.*copilot",
            r"generated\s+by\s+copilot",
            r"\[copilot\]",
            r"github\s+copilot",
            r"\bcopilot\b",
            r"co-pilot",
            r"copilot:",
            r"copilot\s+\w+",  # "copilot sort", "copilot metrics"
        ],
        AIToolType.CURSOR: [
            r"generated\s+by\s+cursor",
            r"\[cursor\]",
            r"cursor\.sh",
            r"cursor\s+ai",
            r"\bcursor\b",
            r"\(cursor\)",
            r"cursor:",
            r"cursor\s+\w+",  # "cursor add", "cursor fix"
        ],
        AIToolType.CLAUDE_CODE: [
            r"generated\s+with\s+claude",
            r"claude\s+code",
            r"\[claude\]",
            r"anthropic\s+claude",
            r"\bclaude\b",
            r"\(claude\)",
            r"claude:",
            r"claude\s+\w+",  # "claude tests", "claude DR"
        ],
        AIToolType.CHATGPT: [
            r"generated\s+by\s+chatgpt",
            r"\[chatgpt\]",
            r"openai\s+gpt",
            r"gpt-4\s+generated",
            r"\bchatgpt\b",
            r"\bopenai\b",
            r"chatgpt:",
            r"openai:",
        ],
        AIToolType.WINDSURF: [
            r"generated\s+by\s+windsurf",
            r"\[windsurf\]",
            r"\bwindsurf\b",
            r"codeium\s+windsurf",
            r"windsurf:",
        ],
        AIToolType.CODY: [
            r"generated\s+by\s+cody",
            r"\[cody\]",
            r"sourcegraph\s+cody",
            r"\bcody\b",
            r"cody:",
        ],
        AIToolType.TABNINE: [
            r"generated\s+by\s+tabnine",
            r"\[tabnine\]",
            r"\btabnine\b",
            r"tab\s+nine",
            r"tabnine:",
        ],
    }

    async def detect(
        self,
        pr_data: dict,
        commits: List[dict],
        diff: str,
    ) -> DetectionResult:
        """
        Detect AI tool from commit message patterns.

        High Confidence: 0.9 (explicit markers in commits)
        Scans all commit messages for AI tool signatures.

        Args:
            pr_data: PR data (not used by this detector)
            commits: List of commit objects
            diff: Unified diff (not used by this detector)

        Returns:
            DetectionResult with confidence 0.9 if pattern found
        """
        for commit in commits:
            msg = (commit.get("commit", {}).get("message") or "").lower()

            for tool, patterns in self.COMMIT_PATTERNS.items():
                # CTO P0: Check for false positive patterns first
                fp_patterns = self.FALSE_POSITIVE_PATTERNS.get(tool, [])
                if any(re.search(p, msg, re.IGNORECASE) for p in fp_patterns):
                    # Skip this tool - false positive detected
                    continue

                for pattern in patterns:
                    match = re.search(pattern, msg, re.IGNORECASE)
                    if match:
                        return DetectionResult(
                            detected=True,
                            confidence=0.9,  # High confidence (explicit marker)
                            tool=tool,
                            method=DetectionMethod.COMMIT_MESSAGE,
                            evidence={
                                "commit_sha": commit.get("sha"),
                                "matched_pattern": pattern,
                                "matched_text": match.group(0),
                                "commit_message_preview": msg[:200],
                            },
                        )

        # No commit pattern found
        return DetectionResult(
            detected=False,
            confidence=0.0,
            tool=None,
            method=DetectionMethod.COMMIT_MESSAGE,
            evidence={"scanned_commits": len(commits)},
        )

    def get_strategy_name(self) -> str:
        return "commit_message"
