"""Initial schema - 24 tables

Revision ID: dce31118ffb7
Revises: 
Create Date: 2025-11-14 16:37:24.786346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce31118ffb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input_tokens', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cost_per_1k_output_tokens', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_id'), 'ai_providers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_providers_is_active'), 'ai_providers', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_providers_provider_type'), 'ai_providers', ['provider_type'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_code', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rego_code', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_is_active'), 'policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_policies_policy_code'), 'policies', ['policy_code'], unique=True)
    op.create_index(op.f('ix_policies_stage'), 'policies', ['stage'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', sa.String(length=1024), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('policy_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_tests_id'), 'policy_tests', ['id'], unique=False)
    op.create_index(op.f('ix_policy_tests_policy_id'), 'policy_tests', ['policy_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('custom_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('base_policy_id', sa.UUID(), nullable=False),
    sa.Column('custom_rego_code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_policies_base_policy_id'), 'custom_policies', ['base_policy_id'], unique=False)
    op.create_index(op.f('ix_custom_policies_id'), 'custom_policies', ['id'], unique=False)
    op.create_index(op.f('ix_custom_policies_project_id'), 'custom_policies', ['project_id'], unique=False)
    op.create_table('gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_name', sa.String(length=255), nullable=False),
    sa.Column('gate_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_created_at'), 'gates', ['created_at'], unique=False)
    op.create_index(op.f('ix_gates_created_by'), 'gates', ['created_by'], unique=False)
    op.create_index(op.f('ix_gates_gate_type'), 'gates', ['gate_type'], unique=False)
    op.create_index(op.f('ix_gates_id'), 'gates', ['id'], unique=False)
    op.create_index(op.f('ix_gates_project_id'), 'gates', ['project_id'], unique=False)
    op.create_index(op.f('ix_gates_stage'), 'gates', ['stage'], unique=False)
    op.create_index(op.f('ix_gates_status'), 'gates', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_is_active'), 'webhooks', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False)
    op.create_index(op.f('ix_webhooks_webhook_url'), 'webhooks', ['webhook_url'], unique=True)
    op.create_table('ai_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_requests_created_at'), 'ai_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_requests_gate_id'), 'ai_requests', ['gate_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_id'), 'ai_requests', ['id'], unique=False)
    op.create_index(op.f('ix_ai_requests_provider_id'), 'ai_requests', ['provider_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_status'), 'ai_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ai_requests_user_id'), 'ai_requests', ['user_id'], unique=False)
    op.create_table('gate_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_approvals_approver_id'), 'gate_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_gate_approvals_gate_id'), 'gate_approvals', ['gate_id'], unique=False)
    op.create_index(op.f('ix_gate_approvals_id'), 'gate_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_gate_approvals_status'), 'gate_approvals', ['status'], unique=False)
    op.create_table('gate_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_bucket', sa.String(length=100), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_gate_evidence_evidence_type'), 'gate_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_gate_evidence_gate_id'), 'gate_evidence', ['gate_id'], unique=False)
    op.create_index(op.f('ix_gate_evidence_id'), 'gate_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_gate_evidence_sha256_hash'), 'gate_evidence', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_gate_evidence_uploaded_at'), 'gate_evidence', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_gate_evidence_uploaded_by'), 'gate_evidence', ['uploaded_by'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_evaluated_at'), 'policy_evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_gate_id'), 'policy_evaluations', ['gate_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_is_passed'), 'policy_evaluations', ['is_passed'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_id'), 'policy_evaluations', ['policy_id'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=False),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('transitioned_by', sa.UUID(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transitioned_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transitions_gate_id'), 'stage_transitions', ['gate_id'], unique=False)
    op.create_index(op.f('ix_stage_transitions_id'), 'stage_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_stage_transitions_transitioned_at'), 'stage_transitions', ['transitioned_at'], unique=False)
    op.create_table('ai_evidence_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('ai_request_id', sa.UUID(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_evidence_drafts_gate_id'), 'ai_evidence_drafts', ['gate_id'], unique=False)
    op.create_index(op.f('ix_ai_evidence_drafts_id'), 'ai_evidence_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_ai_evidence_drafts_is_approved'), 'ai_evidence_drafts', ['is_approved'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ai_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_created_at'), 'ai_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_id'), 'ai_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_month'), 'ai_usage_logs', ['month'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_provider_type'), 'ai_usage_logs', ['provider_type'], unique=False)
    op.create_table('evidence_integrity_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['gate_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_integrity_checks_checked_at'), 'evidence_integrity_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_checks_evidence_id'), 'evidence_integrity_checks', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_checks_id'), 'evidence_integrity_checks', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_integrity_checks_is_valid'), 'evidence_integrity_checks', ['is_valid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_integrity_checks_is_valid'), table_name='evidence_integrity_checks')
    op.drop_index(op.f('ix_evidence_integrity_checks_id'), table_name='evidence_integrity_checks')
    op.drop_index(op.f('ix_evidence_integrity_checks_evidence_id'), table_name='evidence_integrity_checks')
    op.drop_index(op.f('ix_evidence_integrity_checks_checked_at'), table_name='evidence_integrity_checks')
    op.drop_table('evidence_integrity_checks')
    op.drop_index(op.f('ix_ai_usage_logs_provider_type'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_month'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_created_at'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_ai_evidence_drafts_is_approved'), table_name='ai_evidence_drafts')
    op.drop_index(op.f('ix_ai_evidence_drafts_id'), table_name='ai_evidence_drafts')
    op.drop_index(op.f('ix_ai_evidence_drafts_gate_id'), table_name='ai_evidence_drafts')
    op.drop_table('ai_evidence_drafts')
    op.drop_index(op.f('ix_stage_transitions_transitioned_at'), table_name='stage_transitions')
    op.drop_index(op.f('ix_stage_transitions_id'), table_name='stage_transitions')
    op.drop_index(op.f('ix_stage_transitions_gate_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_policy_evaluations_policy_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_is_passed'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_gate_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_evaluated_at'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_gate_evidence_uploaded_by'), table_name='gate_evidence')
    op.drop_index(op.f('ix_gate_evidence_uploaded_at'), table_name='gate_evidence')
    op.drop_index(op.f('ix_gate_evidence_sha256_hash'), table_name='gate_evidence')
    op.drop_index(op.f('ix_gate_evidence_id'), table_name='gate_evidence')
    op.drop_index(op.f('ix_gate_evidence_gate_id'), table_name='gate_evidence')
    op.drop_index(op.f('ix_gate_evidence_evidence_type'), table_name='gate_evidence')
    op.drop_table('gate_evidence')
    op.drop_index(op.f('ix_gate_approvals_status'), table_name='gate_approvals')
    op.drop_index(op.f('ix_gate_approvals_id'), table_name='gate_approvals')
    op.drop_index(op.f('ix_gate_approvals_gate_id'), table_name='gate_approvals')
    op.drop_index(op.f('ix_gate_approvals_approver_id'), table_name='gate_approvals')
    op.drop_table('gate_approvals')
    op.drop_index(op.f('ix_ai_requests_user_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_status'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_provider_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_gate_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_created_at'), table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_index(op.f('ix_webhooks_webhook_url'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_is_active'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_gates_status'), table_name='gates')
    op.drop_index(op.f('ix_gates_stage'), table_name='gates')
    op.drop_index(op.f('ix_gates_project_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_id'), table_name='gates')
    op.drop_index(op.f('ix_gates_gate_type'), table_name='gates')
    op.drop_index(op.f('ix_gates_created_by'), table_name='gates')
    op.drop_index(op.f('ix_gates_created_at'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_custom_policies_project_id'), table_name='custom_policies')
    op.drop_index(op.f('ix_custom_policies_id'), table_name='custom_policies')
    op.drop_index(op.f('ix_custom_policies_base_policy_id'), table_name='custom_policies')
    op.drop_table('custom_policies')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_policy_tests_policy_id'), table_name='policy_tests')
    op.drop_index(op.f('ix_policy_tests_id'), table_name='policy_tests')
    op.drop_table('policy_tests')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_policies_stage'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_code'), table_name='policies')
    op.drop_index(op.f('ix_policies_is_active'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_ai_providers_provider_type'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_is_active'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
