"""
Bundle Builder - Orchestrates IR processing and bundle generation.

Sprint 46: EP-06 IR-Based Backend Scaffold Generation
ADR-023: IR-Based Deterministic Code Generation

Orchestrator that combines all IR processors to generate a complete
runnable backend bundle from an AppBlueprint specification.

Pipeline:
1. Validate IR with IRValidator
2. Run ProjectProcessor (scaffold)
3. Run ModelProcessor (entities)
4. Run EndpointProcessor (CRUD)
5. Collect all files into GeneratedBundle

Design Reference:
    docs/02-design/14-Technical-Specs/IR-Processor-Specification.md

Author: Backend Lead
Date: December 23, 2025
Version: 1.0.0
Status: ACTIVE - Sprint 46 Implementation
"""

from typing import Dict, Any, List, Optional
from pathlib import Path
from datetime import datetime
import logging

from pydantic import BaseModel, Field

from .validator import IRValidator, IRValidationResult
from .processor_base import GeneratedFile, ProcessorResult
from .project_processor import ProjectProcessor
from .model_processor import ModelProcessor
from .endpoint_processor import EndpointProcessor

logger = logging.getLogger(__name__)


class GeneratedBundle(BaseModel):
    """
    Complete generated output bundle.

    Contains all files generated by the IR processing pipeline,
    along with metadata and statistics.
    """

    success: bool = Field(
        description="Whether bundle generation succeeded"
    )
    app_name: str = Field(
        description="Application name from blueprint"
    )
    version: str = Field(
        default="1.0.0",
        description="Application version"
    )
    files: List[GeneratedFile] = Field(
        default_factory=list,
        description="List of generated files"
    )
    file_count: int = Field(
        default=0,
        description="Total number of files generated"
    )
    total_lines: int = Field(
        default=0,
        description="Total lines of code generated"
    )
    errors: List[str] = Field(
        default_factory=list,
        description="List of error messages"
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="List of warning messages"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Generation timestamp"
    )
    generator: str = Field(
        default="SDLC Orchestrator EP-06 IR Processor",
        description="Generator identifier"
    )

    def get_file(self, path: str) -> Optional[GeneratedFile]:
        """Get a file by path."""
        for f in self.files:
            if f.path == path:
                return f
        return None

    def get_files_by_language(self, language: str) -> List[GeneratedFile]:
        """Get all files of a specific language."""
        return [f for f in self.files if f.language == language]

    def to_dict_for_api(self) -> Dict[str, Any]:
        """Convert to API response format."""
        return {
            "success": self.success,
            "app_name": self.app_name,
            "version": self.version,
            "files": {f.path: f.content for f in self.files},
            "file_count": self.file_count,
            "total_lines": self.total_lines,
            "errors": self.errors,
            "warnings": self.warnings,
            "metadata": {
                "generated_at": self.generated_at,
                "generator": self.generator,
            }
        }


class BundleBuilder:
    """
    Orchestrates IR processing and bundle generation.

    Combines validator and all processors to generate a complete
    runnable backend from an AppBlueprint specification.

    Example:
        builder = BundleBuilder(
            schema_dir=Path("schemas"),
            template_dir=Path("templates")
        )

        bundle = builder.build({
            "name": "Restaurant App",
            "version": "1.0.0",
            "modules": [...]
        })

        if bundle.success:
            for file in bundle.files:
                write_file(file.path, file.content)
    """

    def __init__(
        self,
        schema_dir: Optional[Path] = None,
        template_dir: Optional[Path] = None,
    ):
        """
        Initialize bundle builder.

        Args:
            schema_dir: Directory containing JSON schemas (optional)
            template_dir: Directory containing Jinja2 templates
        """
        self.schema_dir = schema_dir
        self.template_dir = template_dir or self._get_default_template_dir()

        # Initialize validator
        self.validator = IRValidator(schema_dir)

        # Initialize processors
        fastapi_template_dir = self.template_dir / "fastapi"
        self.processors = [
            ProjectProcessor(fastapi_template_dir),
            ModelProcessor(fastapi_template_dir),
            EndpointProcessor(fastapi_template_dir),
        ]

    def _get_default_template_dir(self) -> Path:
        """Get default template directory relative to this file."""
        return Path(__file__).parent.parent / "templates"

    def build(self, blueprint: Dict[str, Any]) -> GeneratedBundle:
        """
        Build complete bundle from AppBlueprint.

        This is the main entry point that:
        1. Validates the IR
        2. Runs all processors
        3. Collects results into a bundle

        Args:
            blueprint: Raw AppBlueprint JSON dictionary

        Returns:
            GeneratedBundle with all generated files

        Example:
            bundle = builder.build({
                "name": "My App",
                "version": "1.0.0",
                "modules": [{
                    "name": "products",
                    "entities": [{
                        "name": "Product",
                        "fields": [{"name": "name", "type": "string"}]
                    }]
                }]
            })
        """
        app_name = blueprint.get("name", "unknown")
        version = blueprint.get("version", "1.0.0")
        all_files: List[GeneratedFile] = []
        all_errors: List[str] = []
        all_warnings: List[str] = []

        logger.info(f"Building bundle for: {app_name} v{version}")

        # Step 1: Validate IR
        validation = self.validator.validate_app_blueprint(blueprint)

        if not validation.valid:
            error_messages = [
                f"{issue.path}: {issue.message}"
                for issue in validation.issues
                if issue.severity == "error"
            ]
            warning_messages = [
                f"{issue.path}: {issue.message}"
                for issue in validation.issues
                if issue.severity == "warning"
            ]

            logger.error(f"IR validation failed: {len(error_messages)} errors")
            return GeneratedBundle(
                success=False,
                app_name=app_name,
                version=version,
                files=[],
                file_count=0,
                total_lines=0,
                errors=error_messages,
                warnings=warning_messages,
            )

        normalized_ir = validation.normalized_ir
        logger.info(f"IR validation passed, normalized blueprint")

        # Collect non-error validation issues as warnings
        all_warnings.extend([
            f"{issue.path}: {issue.message}"
            for issue in validation.issues
            if issue.severity == "warning"
        ])

        # Step 2: Run processors
        for processor in self.processors:
            logger.info(f"Running processor: {processor.name}")

            try:
                result = processor.process(normalized_ir)
                all_files.extend(result.files)
                all_errors.extend(result.errors)
                all_warnings.extend(result.warnings)

                logger.info(
                    f"Processor {processor.name}: "
                    f"{len(result.files)} files, "
                    f"{len(result.errors)} errors"
                )

            except Exception as e:
                logger.exception(f"Processor {processor.name} failed: {e}")
                all_errors.append(f"Processor {processor.name} failed: {str(e)}")

        # Step 3: Calculate statistics
        file_count = len(all_files)
        total_lines = sum(
            len(f.content.split("\n"))
            for f in all_files
        )

        # Determine success
        success = len(all_errors) == 0

        logger.info(
            f"Bundle {'completed' if success else 'failed'}: "
            f"{file_count} files, {total_lines} lines"
        )

        return GeneratedBundle(
            success=success,
            app_name=normalized_ir.get("name", app_name),
            version=normalized_ir.get("version", version),
            files=all_files,
            file_count=file_count,
            total_lines=total_lines,
            errors=all_errors,
            warnings=all_warnings,
        )

    def build_preview(self, blueprint: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate a preview of what would be built.

        Returns file paths and line counts without full content.

        Args:
            blueprint: Raw AppBlueprint JSON dictionary

        Returns:
            Preview dictionary with file info
        """
        bundle = self.build(blueprint)

        return {
            "success": bundle.success,
            "app_name": bundle.app_name,
            "version": bundle.version,
            "file_count": bundle.file_count,
            "total_lines": bundle.total_lines,
            "files": [
                {
                    "path": f.path,
                    "language": f.language,
                    "lines": len(f.content.split("\n")),
                }
                for f in bundle.files
            ],
            "errors": bundle.errors,
            "warnings": bundle.warnings,
        }
