"""
Model Processor - Generates SQLAlchemy models and Pydantic schemas.

Sprint 46: EP-06 IR-Based Backend Scaffold Generation
ADR-023: IR-Based Deterministic Code Generation

Generates database layer code from entity specifications:
- SQLAlchemy models with relationships
- Pydantic schemas (Create, Read, Update, List)
- Package __init__.py files with exports

Design Reference:
    docs/02-design/14-Technical-Specs/IR-Processor-Specification.md

Author: Backend Lead
Date: December 23, 2025
Version: 1.0.0
Status: ACTIVE - Sprint 46 Implementation
"""

from typing import Dict, Any, List
from pathlib import Path
import logging

from .processor_base import IRProcessor, ProcessorResult, GeneratedFile

logger = logging.getLogger(__name__)


class ModelProcessor(IRProcessor):
    """
    Generates SQLAlchemy models and Pydantic schemas.

    This processor creates:
    - app/models/{entity}.py: SQLAlchemy ORM models
    - app/schemas/{entity}.py: Pydantic validation schemas
    - app/models/__init__.py: Model exports
    - app/schemas/__init__.py: Schema exports

    Example:
        processor = ModelProcessor(template_dir=Path("templates/fastapi"))
        result = processor.process(normalized_ir)
        for f in result.files:
            print(f"{f.path}: {len(f.content)} chars")
    """

    @property
    def name(self) -> str:
        return "model"

    def process(self, ir: Dict[str, Any]) -> ProcessorResult:
        """
        Generate model and schema files.

        Args:
            ir: Normalized IR (AppBlueprint)

        Returns:
            ProcessorResult with model and schema files
        """
        files: List[GeneratedFile] = []
        errors: List[str] = []

        try:
            entities = self._get_all_entities(ir)

            if not entities:
                logger.warning("No entities found in IR")
                return ProcessorResult(
                    success=True,
                    files=files,
                    warnings=["No entities found in blueprint"]
                )

            # Generate model for each entity
            for entity in entities:
                model_name = self._get_model_filename(entity)

                # Generate SQLAlchemy model
                files.append(GeneratedFile(
                    path=f"app/models/{model_name}.py",
                    content=self.render_template("model.py.j2", {
                        "entity": entity,
                    })
                ))

                # Generate Pydantic schema
                files.append(GeneratedFile(
                    path=f"app/schemas/{model_name}.py",
                    content=self.render_template("schema.py.j2", {
                        "entity": entity,
                    })
                ))

            # Generate models __init__.py
            files.append(GeneratedFile(
                path="app/models/__init__.py",
                content=self._generate_models_init(entities)
            ))

            # Generate schemas __init__.py
            files.append(GeneratedFile(
                path="app/schemas/__init__.py",
                content=self._generate_schemas_init(entities)
            ))

            logger.info(f"ModelProcessor generated {len(files)} files for {len(entities)} entities")
            return ProcessorResult(success=True, files=files)

        except Exception as e:
            logger.exception(f"ModelProcessor error: {e}")
            errors.append(f"ModelProcessor failed: {str(e)}")
            return ProcessorResult(success=False, files=files, errors=errors)

    def _get_model_filename(self, entity: Dict[str, Any]) -> str:
        """
        Get model filename from entity.

        Converts table_name to singular form for filename.
        Examples: employees→employee, categories→category, addresses→address
        """
        table_name = entity.get("table_name", "")
        if not table_name:
            return table_name
        # "ies" → "y": categories → category, companies → company
        if table_name.endswith("ies") and len(table_name) > 3:
            return table_name[:-3] + "y"
        # "es" → strip only when base ends in s/sh/ch/x/z
        if table_name.endswith("es") and len(table_name) > 2:
            base = table_name[:-2]
            if base.endswith(("s", "sh", "ch", "x", "z")):
                return base  # addresses→address, statuses→status, boxes→box
        # Default: strip trailing "s"
        if table_name.endswith("s") and not table_name.endswith("ss"):
            return table_name[:-1]  # users→user, employees→employee
        return table_name

    def _generate_models_init(self, entities: List[Dict]) -> str:
        """Generate models/__init__.py content."""
        lines = [
            '"""SQLAlchemy models package.',
            '',
            'Generated by SDLC Orchestrator EP-06 IR Processor.',
            '"""',
            'from app.core.database import Base',
            '',
        ]

        # Import each model
        for entity in entities:
            model_file = self._get_model_filename(entity)
            lines.append(f"from .{model_file} import {entity['name']}")

        lines.append('')

        # Export all
        exports = ["Base"] + [e["name"] for e in entities]
        lines.append(f"__all__ = {exports}")
        lines.append('')

        return '\n'.join(lines)

    def _generate_schemas_init(self, entities: List[Dict]) -> str:
        """Generate schemas/__init__.py content."""
        lines = [
            '"""Pydantic schemas package.',
            '',
            'Generated by SDLC Orchestrator EP-06 IR Processor.',
            '"""',
            '',
        ]

        # Import each schema set
        for entity in entities:
            schema_file = self._get_model_filename(entity)
            name = entity['name']
            lines.append(
                f"from .{schema_file} import ("
            )
            lines.append(f"    {name}Create,")
            lines.append(f"    {name}Read,")
            lines.append(f"    {name}Update,")
            lines.append(f"    {name}List,")
            lines.append(")")

        lines.append('')

        # Export all
        exports = []
        for entity in entities:
            name = entity["name"]
            exports.extend([
                f"{name}Create",
                f"{name}Read",
                f"{name}Update",
                f"{name}List",
            ])

        lines.append(f"__all__ = {exports}")
        lines.append('')

        return '\n'.join(lines)
