/**
 * =========================================================================
 * QualityReportGenerator - Quality Report Generation Components
 * SDLC Orchestrator - Sprint 55 Day 5
 *
 * Version: 1.0.0
 * Date: December 26, 2025
 * Status: ACTIVE - Sprint 55 Implementation
 *
 * Purpose:
 * - Generate comprehensive quality reports
 * - Aggregate pipeline results into structured reports
 * - Provide report metadata and timestamps
 * - Support multiple output formats
 *
 * References:
 * - docs/02-design/14-Technical-Specs/Quality-Gates-Codegen-Specification.md
 * =========================================================================
 */

import { useMemo, useState, useCallback } from "react";
import {
  FileText,
  Download,
  Clock,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  FileJson,
  FileSpreadsheet,
  Printer,
  Share2,
  Copy,
  Check,
  Calendar,
  User,
  Building2,
  GitBranch,
  Hash,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
  DropdownMenuLabel,
} from "@/components/ui/dropdown-menu";
import type {
  PipelineResult,
  GateResult,
} from "@/types/quality";
import {
  isSyntaxResult,
  isSecurityResult,
  isArchitectureResult,
  isTestResult,
  GATE_CONFIGS,
} from "@/types/quality";

// ============================================================================
// Types
// ============================================================================

export interface ReportMetadata {
  /** Report ID */
  id: string;
  /** Report title */
  title: string;
  /** Project name */
  projectName?: string;
  /** Branch name */
  branchName?: string;
  /** Commit hash */
  commitHash?: string;
  /** Generated by (user) */
  generatedBy?: string;
  /** Generation timestamp */
  generatedAt: Date;
  /** Report version */
  version: string;
}

export interface QualityReport {
  /** Report metadata */
  metadata: ReportMetadata;
  /** Pipeline result */
  pipelineResult: PipelineResult;
  /** Computed quality score (0-100) */
  qualityScore: number;
  /** Quality grade (A-F) */
  qualityGrade: string;
  /** Issue summary by severity */
  issueSummary: {
    critical: number;
    high: number;
    medium: number;
    low: number;
    total: number;
  };
  /** Gate summary */
  gateSummary: {
    passed: number;
    failed: number;
    skipped: number;
    total: number;
  };
  /** Files analyzed */
  filesAnalyzed: number;
  /** Total duration */
  totalDurationMs: number;
  /** Recommendations */
  recommendations: ReportRecommendation[];
}

export interface ReportRecommendation {
  /** Priority (1=highest) */
  priority: number;
  /** Category */
  category: "security" | "syntax" | "architecture" | "tests" | "general";
  /** Title */
  title: string;
  /** Vietnamese title */
  vietnameseTitle: string;
  /** Description */
  description: string;
  /** Vietnamese description */
  vietnameseDescription: string;
}

export type ExportFormat = "json" | "csv" | "pdf" | "markdown";

interface QualityReportGeneratorProps {
  /** Pipeline result to generate report from */
  result: PipelineResult;
  /** Report metadata */
  metadata?: Partial<ReportMetadata>;
  /** Use Vietnamese labels */
  vietnamese?: boolean;
  /** Show export controls */
  showExport?: boolean;
  /** Export handler */
  onExport?: (format: ExportFormat, report: QualityReport) => void;
  /** Share handler */
  onShare?: (report: QualityReport) => void;
  /** Print handler */
  onPrint?: (report: QualityReport) => void;
  /** Additional class name */
  className?: string;
}

// ============================================================================
// Report Generation Functions
// ============================================================================

function generateReportId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 8);
  return `QR-${timestamp}-${random}`.toUpperCase();
}

function calculateQualityScore(result: PipelineResult): number {
  let score = 100;
  let penalty = 0;

  for (const gate of result.gates) {
    if (gate.status === "failed") {
      penalty += 25;
    } else if (gate.status === "skipped") {
      penalty += 5;
    }

    if (isSecurityResult(gate.details)) {
      penalty += gate.details.criticalCount * 10;
      penalty += gate.details.highCount * 5;
      penalty += gate.details.mediumCount * 2;
      penalty += gate.details.lowCount * 0.5;
    }

    if (isSyntaxResult(gate.details)) {
      const errorRate =
        (gate.details.filesChecked - gate.details.filesPassed) /
        Math.max(gate.details.filesChecked, 1);
      penalty += errorRate * 20;
    }

    if (isTestResult(gate.details)) {
      const failRate =
        gate.details.testsFailed / Math.max(gate.details.testsRun, 1);
      penalty += failRate * 15;
    }

    if (isArchitectureResult(gate.details)) {
      penalty += gate.details.issues.length * 3;
    }
  }

  return Math.max(0, Math.min(100, Math.round(score - penalty)));
}

function getQualityGrade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

function getIssueSummary(result: PipelineResult): QualityReport["issueSummary"] {
  const summary = { critical: 0, high: 0, medium: 0, low: 0, total: 0 };

  for (const gate of result.gates) {
    if (isSecurityResult(gate.details)) {
      summary.critical += gate.details.criticalCount;
      summary.high += gate.details.highCount;
      summary.medium += gate.details.mediumCount;
      summary.low += gate.details.lowCount;
    }
    if (isSyntaxResult(gate.details)) {
      summary.high += gate.details.issues.length;
    }
    if (isArchitectureResult(gate.details)) {
      summary.medium += gate.details.issues.length;
    }
    if (isTestResult(gate.details)) {
      summary.high += gate.details.testsFailed;
    }
  }

  summary.total = summary.critical + summary.high + summary.medium + summary.low;
  return summary;
}

function getGateSummary(result: PipelineResult): QualityReport["gateSummary"] {
  const summary = { passed: 0, failed: 0, skipped: 0, total: result.gates.length };

  for (const gate of result.gates) {
    if (gate.status === "passed") summary.passed++;
    else if (gate.status === "failed") summary.failed++;
    else if (gate.status === "skipped") summary.skipped++;
  }

  return summary;
}

function getFilesAnalyzed(result: PipelineResult): number {
  let files = 0;

  for (const gate of result.gates) {
    if (isSyntaxResult(gate.details)) {
      files = Math.max(files, gate.details.filesChecked);
    }
  }

  return files;
}

function generateRecommendations(
  result: PipelineResult,
  issueSummary: QualityReport["issueSummary"]
): ReportRecommendation[] {
  const recommendations: ReportRecommendation[] = [];
  let priority = 1;

  // Critical security issues
  if (issueSummary.critical > 0) {
    recommendations.push({
      priority: priority++,
      category: "security",
      title: "Fix Critical Security Vulnerabilities",
      vietnameseTitle: "Sửa lỗ hổng bảo mật nghiêm trọng",
      description: `${issueSummary.critical} critical security issue(s) must be addressed immediately before deployment.`,
      vietnameseDescription: `${issueSummary.critical} lỗ hổng bảo mật nghiêm trọng cần được khắc phục ngay trước khi triển khai.`,
    });
  }

  // High severity issues
  if (issueSummary.high > 0) {
    recommendations.push({
      priority: priority++,
      category: "general",
      title: "Address High Severity Issues",
      vietnameseTitle: "Khắc phục vấn đề mức độ cao",
      description: `${issueSummary.high} high severity issue(s) should be fixed before release.`,
      vietnameseDescription: `${issueSummary.high} vấn đề mức độ cao nên được sửa trước khi phát hành.`,
    });
  }

  // Failed gates
  for (const gate of result.gates) {
    if (gate.status === "failed") {
      const config = GATE_CONFIGS[gate.gateName];
      recommendations.push({
        priority: priority++,
        category: gate.gateName,
        title: `Fix ${config.label} Gate Failures`,
        vietnameseTitle: `Sửa lỗi cổng ${config.vietnameseLabel}`,
        description: `The ${config.label.toLowerCase()} validation gate failed. Review and fix the reported issues.`,
        vietnameseDescription: `Cổng xác thực ${config.vietnameseLabel.toLowerCase()} đã thất bại. Xem xét và sửa các vấn đề được báo cáo.`,
      });
    }
  }

  // Test coverage
  for (const gate of result.gates) {
    if (gate.gateName === "tests" && isTestResult(gate.details)) {
      const passRate = gate.details.testsRun > 0
        ? (gate.details.testsPassed / gate.details.testsRun) * 100
        : 0;

      if (passRate < 80) {
        recommendations.push({
          priority: priority++,
          category: "tests",
          title: "Improve Test Coverage",
          vietnameseTitle: "Cải thiện độ phủ kiểm thử",
          description: `Test pass rate is ${passRate.toFixed(1)}%. Aim for at least 80% test coverage.`,
          vietnameseDescription: `Tỷ lệ kiểm thử đạt là ${passRate.toFixed(1)}%. Hướng tới ít nhất 80% độ phủ kiểm thử.`,
        });
      }
    }
  }

  // Add general recommendation if all passed
  if (recommendations.length === 0) {
    recommendations.push({
      priority: 1,
      category: "general",
      title: "Code Quality Excellent",
      vietnameseTitle: "Chất lượng code xuất sắc",
      description: "All quality gates passed. Code is ready for review and deployment.",
      vietnameseDescription: "Tất cả các cổng chất lượng đã đạt. Code sẵn sàng để review và triển khai.",
    });
  }

  return recommendations;
}

function generateReport(
  result: PipelineResult,
  metadata: Partial<ReportMetadata> = {}
): QualityReport {
  const qualityScore = calculateQualityScore(result);
  const issueSummary = getIssueSummary(result);

  return {
    metadata: {
      id: metadata.id || generateReportId(),
      title: metadata.title || "Quality Pipeline Report",
      projectName: metadata.projectName,
      branchName: metadata.branchName,
      commitHash: metadata.commitHash,
      generatedBy: metadata.generatedBy,
      generatedAt: metadata.generatedAt || new Date(),
      version: metadata.version || "1.0.0",
    },
    pipelineResult: result,
    qualityScore,
    qualityGrade: getQualityGrade(qualityScore),
    issueSummary,
    gateSummary: getGateSummary(result),
    filesAnalyzed: getFilesAnalyzed(result),
    totalDurationMs: result.totalDurationMs,
    recommendations: generateRecommendations(result, issueSummary),
  };
}

// ============================================================================
// Export Functions
// ============================================================================

export function exportReportAsJSON(report: QualityReport): string {
  return JSON.stringify(report, null, 2);
}

export function exportReportAsCSV(report: QualityReport): string {
  const lines: string[] = [];

  // Header
  lines.push("Quality Report Export");
  lines.push(`Report ID,${report.metadata.id}`);
  lines.push(`Generated At,${report.metadata.generatedAt.toISOString()}`);
  lines.push(`Quality Score,${report.qualityScore}`);
  lines.push(`Quality Grade,${report.qualityGrade}`);
  lines.push("");

  // Issue Summary
  lines.push("Issue Summary");
  lines.push("Severity,Count");
  lines.push(`Critical,${report.issueSummary.critical}`);
  lines.push(`High,${report.issueSummary.high}`);
  lines.push(`Medium,${report.issueSummary.medium}`);
  lines.push(`Low,${report.issueSummary.low}`);
  lines.push(`Total,${report.issueSummary.total}`);
  lines.push("");

  // Gate Summary
  lines.push("Gate Summary");
  lines.push("Gate,Status,Duration (ms)");
  for (const gate of report.pipelineResult.gates) {
    lines.push(`${gate.gateName},${gate.status},${gate.durationMs}`);
  }
  lines.push("");

  // Recommendations
  lines.push("Recommendations");
  lines.push("Priority,Category,Title,Description");
  for (const rec of report.recommendations) {
    lines.push(`${rec.priority},${rec.category},"${rec.title}","${rec.description}"`);
  }

  return lines.join("\n");
}

export function exportReportAsMarkdown(report: QualityReport, vietnamese = false): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${vietnamese ? "Báo cáo chất lượng" : "Quality Report"}`);
  lines.push("");

  // Metadata
  lines.push(`## ${vietnamese ? "Thông tin báo cáo" : "Report Information"}`);
  lines.push(`- **${vietnamese ? "Mã báo cáo" : "Report ID"}:** ${report.metadata.id}`);
  lines.push(`- **${vietnamese ? "Ngày tạo" : "Generated At"}:** ${report.metadata.generatedAt.toLocaleString()}`);
  if (report.metadata.projectName) {
    lines.push(`- **${vietnamese ? "Dự án" : "Project"}:** ${report.metadata.projectName}`);
  }
  if (report.metadata.branchName) {
    lines.push(`- **${vietnamese ? "Nhánh" : "Branch"}:** ${report.metadata.branchName}`);
  }
  if (report.metadata.commitHash) {
    lines.push(`- **${vietnamese ? "Commit" : "Commit"}:** \`${report.metadata.commitHash}\``);
  }
  lines.push("");

  // Score
  lines.push(`## ${vietnamese ? "Điểm chất lượng" : "Quality Score"}`);
  lines.push(`**${report.qualityScore}/100** (${vietnamese ? "Hạng" : "Grade"}: **${report.qualityGrade}**)`);
  lines.push("");

  // Issue Summary
  lines.push(`## ${vietnamese ? "Tóm tắt vấn đề" : "Issue Summary"}`);
  lines.push(`| ${vietnamese ? "Mức độ" : "Severity"} | ${vietnamese ? "Số lượng" : "Count"} |`);
  lines.push("|----------|-------|");
  lines.push(`| ${vietnamese ? "Nghiêm trọng" : "Critical"} | ${report.issueSummary.critical} |`);
  lines.push(`| ${vietnamese ? "Cao" : "High"} | ${report.issueSummary.high} |`);
  lines.push(`| ${vietnamese ? "Trung bình" : "Medium"} | ${report.issueSummary.medium} |`);
  lines.push(`| ${vietnamese ? "Thấp" : "Low"} | ${report.issueSummary.low} |`);
  lines.push(`| **${vietnamese ? "Tổng" : "Total"}** | **${report.issueSummary.total}** |`);
  lines.push("");

  // Gate Results
  lines.push(`## ${vietnamese ? "Kết quả cổng" : "Gate Results"}`);
  lines.push(`| ${vietnamese ? "Cổng" : "Gate"} | ${vietnamese ? "Trạng thái" : "Status"} | ${vietnamese ? "Thời gian" : "Duration"} |`);
  lines.push("|------|--------|----------|");
  for (const gate of report.pipelineResult.gates) {
    const config = GATE_CONFIGS[gate.gateName];
    const status = gate.status === "passed" ? "Passed" : gate.status === "failed" ? "Failed" : gate.status;
    const statusEmoji = gate.status === "passed" ? "" : gate.status === "failed" ? "" : "";
    lines.push(`| ${vietnamese ? config.vietnameseLabel : config.label} | ${statusEmoji} ${status} | ${gate.durationMs}ms |`);
  }
  lines.push("");

  // Recommendations
  lines.push(`## ${vietnamese ? "Khuyến nghị" : "Recommendations"}`);
  for (const rec of report.recommendations) {
    lines.push(`### ${rec.priority}. ${vietnamese ? rec.vietnameseTitle : rec.title}`);
    lines.push(vietnamese ? rec.vietnameseDescription : rec.description);
    lines.push("");
  }

  return lines.join("\n");
}

// ============================================================================
// Sub-Components
// ============================================================================

interface ReportHeaderProps {
  report: QualityReport;
  vietnamese?: boolean;
}

function ReportHeader({ report, vietnamese = false }: ReportHeaderProps) {
  const [copied, setCopied] = useState(false);

  const handleCopyId = useCallback(() => {
    navigator.clipboard.writeText(report.metadata.id);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [report.metadata.id]);

  return (
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
      <div>
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-muted-foreground" />
          <h2 className="text-xl font-semibold">
            {vietnamese ? "Báo cáo chất lượng" : "Quality Report"}
          </h2>
        </div>
        <div className="flex items-center gap-2 mt-1">
          <Badge variant="outline" className="font-mono text-xs">
            {report.metadata.id}
          </Badge>
          <Button
            variant="ghost"
            size="icon"
            className="h-6 w-6"
            onClick={handleCopyId}
          >
            {copied ? (
              <Check className="h-3 w-3 text-green-500" />
            ) : (
              <Copy className="h-3 w-3" />
            )}
          </Button>
        </div>
      </div>

      <div className="flex flex-wrap gap-4 text-sm text-muted-foreground">
        <div className="flex items-center gap-1.5">
          <Calendar className="h-4 w-4" />
          <span>{report.metadata.generatedAt.toLocaleString()}</span>
        </div>
        {report.metadata.generatedBy && (
          <div className="flex items-center gap-1.5">
            <User className="h-4 w-4" />
            <span>{report.metadata.generatedBy}</span>
          </div>
        )}
        {report.metadata.projectName && (
          <div className="flex items-center gap-1.5">
            <Building2 className="h-4 w-4" />
            <span>{report.metadata.projectName}</span>
          </div>
        )}
        {report.metadata.branchName && (
          <div className="flex items-center gap-1.5">
            <GitBranch className="h-4 w-4" />
            <span>{report.metadata.branchName}</span>
          </div>
        )}
        {report.metadata.commitHash && (
          <div className="flex items-center gap-1.5">
            <Hash className="h-4 w-4" />
            <span className="font-mono">{report.metadata.commitHash.substring(0, 7)}</span>
          </div>
        )}
      </div>
    </div>
  );
}

interface ScoreSummaryProps {
  report: QualityReport;
  vietnamese?: boolean;
}

function ScoreSummary({ report, vietnamese = false }: ScoreSummaryProps) {
  const gradeColors: Record<string, { text: string; bg: string; border: string }> = {
    A: { text: "text-green-600", bg: "bg-green-100 dark:bg-green-900/30", border: "border-green-500" },
    B: { text: "text-blue-600", bg: "bg-blue-100 dark:bg-blue-900/30", border: "border-blue-500" },
    C: { text: "text-yellow-600", bg: "bg-yellow-100 dark:bg-yellow-900/30", border: "border-yellow-500" },
    D: { text: "text-orange-600", bg: "bg-orange-100 dark:bg-orange-900/30", border: "border-orange-500" },
    F: { text: "text-red-600", bg: "bg-red-100 dark:bg-red-900/30", border: "border-red-500" },
  };

  const colors = gradeColors[report.qualityGrade] || gradeColors['F'];

  return (
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      {/* Quality Score */}
      <Card className={cn("relative overflow-hidden", colors?.bg)}>
        <CardContent className="pt-4">
          <div className="text-sm text-muted-foreground mb-1">
            {vietnamese ? "Điểm chất lượng" : "Quality Score"}
          </div>
          <div className="flex items-end gap-2">
            <span className={cn("text-4xl font-bold", colors?.text)}>
              {report.qualityScore}
            </span>
            <span className="text-lg text-muted-foreground mb-1">/100</span>
          </div>
          <Badge variant="outline" className={cn("mt-2", colors?.text, colors?.border)}>
            {vietnamese ? "Hạng" : "Grade"} {report.qualityGrade}
          </Badge>
        </CardContent>
      </Card>

      {/* Gates Summary */}
      <Card>
        <CardContent className="pt-4">
          <div className="text-sm text-muted-foreground mb-1">
            {vietnamese ? "Cổng đạt" : "Gates Passed"}
          </div>
          <div className="flex items-end gap-2">
            <span className="text-4xl font-bold text-green-600">
              {report.gateSummary.passed}
            </span>
            <span className="text-lg text-muted-foreground mb-1">
              /{report.gateSummary.total}
            </span>
          </div>
          {report.gateSummary.failed > 0 && (
            <Badge variant="destructive" className="mt-2">
              {report.gateSummary.failed} {vietnamese ? "thất bại" : "failed"}
            </Badge>
          )}
        </CardContent>
      </Card>

      {/* Issues */}
      <Card>
        <CardContent className="pt-4">
          <div className="text-sm text-muted-foreground mb-1">
            {vietnamese ? "Tổng vấn đề" : "Total Issues"}
          </div>
          <div className="text-4xl font-bold">
            {report.issueSummary.total}
          </div>
          {report.issueSummary.critical > 0 && (
            <Badge variant="destructive" className="mt-2">
              {report.issueSummary.critical} {vietnamese ? "nghiêm trọng" : "critical"}
            </Badge>
          )}
        </CardContent>
      </Card>

      {/* Duration */}
      <Card>
        <CardContent className="pt-4">
          <div className="text-sm text-muted-foreground mb-1">
            {vietnamese ? "Thời gian" : "Duration"}
          </div>
          <div className="text-4xl font-bold">
            {(report.totalDurationMs / 1000).toFixed(1)}
          </div>
          <span className="text-sm text-muted-foreground">
            {vietnamese ? "giây" : "seconds"}
          </span>
        </CardContent>
      </Card>
    </div>
  );
}

interface RecommendationsListProps {
  recommendations: ReportRecommendation[];
  vietnamese?: boolean;
}

function RecommendationsList({ recommendations, vietnamese = false }: RecommendationsListProps) {
  const categoryIcons: Record<string, typeof AlertTriangle> = {
    security: AlertTriangle,
    syntax: FileText,
    architecture: Building2,
    tests: CheckCircle2,
    general: AlertTriangle,
  };

  const categoryColors: Record<string, string> = {
    security: "text-red-500",
    syntax: "text-yellow-500",
    architecture: "text-blue-500",
    tests: "text-green-500",
    general: "text-gray-500",
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg flex items-center gap-2">
          <AlertTriangle className="h-5 w-5" />
          {vietnamese ? "Khuyến nghị" : "Recommendations"}
        </CardTitle>
        <CardDescription>
          {vietnamese
            ? "Các bước tiếp theo được đề xuất dựa trên kết quả phân tích"
            : "Suggested next steps based on analysis results"}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {recommendations.map((rec, index) => {
            const Icon = categoryIcons[rec.category] || AlertTriangle;
            const color = categoryColors[rec.category] || "text-gray-500";

            return (
              <div
                key={index}
                className="flex gap-4 p-3 rounded-lg bg-muted/30"
              >
                <div className={cn("flex-shrink-0", color)}>
                  <Icon className="h-5 w-5" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      #{rec.priority}
                    </Badge>
                    <Badge variant="secondary" className="text-xs capitalize">
                      {rec.category}
                    </Badge>
                  </div>
                  <h4 className="font-medium mt-1">
                    {vietnamese ? rec.vietnameseTitle : rec.title}
                  </h4>
                  <p className="text-sm text-muted-foreground mt-1">
                    {vietnamese ? rec.vietnameseDescription : rec.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

interface GateDetailsTableProps {
  gates: GateResult[];
  vietnamese?: boolean;
}

function GateDetailsTable({ gates, vietnamese = false }: GateDetailsTableProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">
          {vietnamese ? "Chi tiết cổng" : "Gate Details"}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b">
                <th className="text-left py-2 px-3">
                  {vietnamese ? "Cổng" : "Gate"}
                </th>
                <th className="text-left py-2 px-3">
                  {vietnamese ? "Trạng thái" : "Status"}
                </th>
                <th className="text-right py-2 px-3">
                  {vietnamese ? "Thời gian" : "Duration"}
                </th>
                <th className="text-right py-2 px-3">
                  {vietnamese ? "Vấn đề" : "Issues"}
                </th>
              </tr>
            </thead>
            <tbody>
              {gates.map((gate) => {
                const config = GATE_CONFIGS[gate.gateName];
                let issueCount = 0;

                if (isSyntaxResult(gate.details)) {
                  issueCount = gate.details.issues.length;
                } else if (isSecurityResult(gate.details)) {
                  issueCount = gate.details.issues.length;
                } else if (isArchitectureResult(gate.details)) {
                  issueCount = gate.details.issues.length;
                } else if (isTestResult(gate.details)) {
                  issueCount = gate.details.testsFailed;
                }

                return (
                  <tr key={gate.gateName} className="border-b last:border-0">
                    <td className="py-2 px-3 font-medium">
                      {vietnamese ? config.vietnameseLabel : config.label}
                    </td>
                    <td className="py-2 px-3">
                      <div className="flex items-center gap-2">
                        {gate.status === "passed" ? (
                          <CheckCircle2 className="h-4 w-4 text-green-500" />
                        ) : gate.status === "failed" ? (
                          <XCircle className="h-4 w-4 text-red-500" />
                        ) : (
                          <Clock className="h-4 w-4 text-gray-400" />
                        )}
                        <span
                          className={cn(
                            gate.status === "passed" && "text-green-600",
                            gate.status === "failed" && "text-red-600"
                          )}
                        >
                          {gate.status === "passed"
                            ? vietnamese ? "Đạt" : "Passed"
                            : gate.status === "failed"
                              ? vietnamese ? "Thất bại" : "Failed"
                              : gate.status}
                        </span>
                      </div>
                    </td>
                    <td className="py-2 px-3 text-right font-mono">
                      {gate.durationMs}ms
                    </td>
                    <td className="py-2 px-3 text-right">
                      {issueCount > 0 ? (
                        <Badge variant="destructive">{issueCount}</Badge>
                      ) : (
                        <span className="text-muted-foreground">-</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}

interface ExportControlsProps {
  report: QualityReport;
  vietnamese?: boolean;
  onExport?: (format: ExportFormat, report: QualityReport) => void;
  onShare?: (report: QualityReport) => void;
  onPrint?: (report: QualityReport) => void;
}

function ExportControls({
  report,
  vietnamese = false,
  onExport,
  onShare,
  onPrint,
}: ExportControlsProps) {
  const handleExport = useCallback(
    (format: ExportFormat) => {
      if (onExport) {
        onExport(format, report);
      } else {
        // Default export behavior
        let content: string;
        let filename: string;
        let mimeType: string;

        switch (format) {
          case "json":
            content = exportReportAsJSON(report);
            filename = `quality-report-${report.metadata.id}.json`;
            mimeType = "application/json";
            break;
          case "csv":
            content = exportReportAsCSV(report);
            filename = `quality-report-${report.metadata.id}.csv`;
            mimeType = "text/csv";
            break;
          case "markdown":
            content = exportReportAsMarkdown(report, vietnamese);
            filename = `quality-report-${report.metadata.id}.md`;
            mimeType = "text/markdown";
            break;
          default:
            return;
        }

        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }
    },
    [report, vietnamese, onExport]
  );

  return (
    <div className="flex items-center gap-2">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="sm">
            <Download className="h-4 w-4 mr-2" />
            {vietnamese ? "Xuất báo cáo" : "Export"}
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuLabel>
            {vietnamese ? "Chọn định dạng" : "Select Format"}
          </DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={() => handleExport("json")}>
            <FileJson className="h-4 w-4 mr-2" />
            JSON
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => handleExport("csv")}>
            <FileSpreadsheet className="h-4 w-4 mr-2" />
            CSV
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => handleExport("markdown")}>
            <FileText className="h-4 w-4 mr-2" />
            Markdown
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {onPrint && (
        <Button variant="outline" size="sm" onClick={() => onPrint(report)}>
          <Printer className="h-4 w-4 mr-2" />
          {vietnamese ? "In" : "Print"}
        </Button>
      )}

      {onShare && (
        <Button variant="outline" size="sm" onClick={() => onShare(report)}>
          <Share2 className="h-4 w-4 mr-2" />
          {vietnamese ? "Chia sẻ" : "Share"}
        </Button>
      )}
    </div>
  );
}

// ============================================================================
// Main Component
// ============================================================================

export function QualityReportGenerator({
  result,
  metadata = {},
  vietnamese = false,
  showExport = true,
  onExport,
  onShare,
  onPrint,
  className,
}: QualityReportGeneratorProps) {
  const report = useMemo(
    () => generateReport(result, metadata),
    [result, metadata]
  );

  return (
    <div className={cn("space-y-6", className)}>
      {/* Header */}
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <ReportHeader report={report} vietnamese={vietnamese} />
        {showExport && (
          <ExportControls
            report={report}
            vietnamese={vietnamese}
            onExport={onExport}
            onShare={onShare}
            onPrint={onPrint}
          />
        )}
      </div>

      <Separator />

      {/* Score Summary */}
      <ScoreSummary report={report} vietnamese={vietnamese} />

      {/* Tabs for Details */}
      <Tabs defaultValue="recommendations" className="w-full">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="recommendations">
            {vietnamese ? "Khuyến nghị" : "Recommendations"}
          </TabsTrigger>
          <TabsTrigger value="details">
            {vietnamese ? "Chi tiết" : "Details"}
          </TabsTrigger>
        </TabsList>
        <TabsContent value="recommendations" className="mt-4">
          <RecommendationsList
            recommendations={report.recommendations}
            vietnamese={vietnamese}
          />
        </TabsContent>
        <TabsContent value="details" className="mt-4">
          <GateDetailsTable
            gates={report.pipelineResult.gates}
            vietnamese={vietnamese}
          />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// ============================================================================
// Export
// ============================================================================

export default QualityReportGenerator;
export { generateReport, generateReportId };
